import { mkdirSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'

const ROOT = new URL('../../', import.meta.url).pathname.replace(/\/$/, '')

export function deriveTitle(gameId: string): string {
  return gameId
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function write(filePath: string, content: string): void {
  mkdirSync(join(filePath, '..'), { recursive: true })
  writeFileSync(filePath, content)
}

export async function scaffoldNewGame(gameId: string, title?: string, options: { log?: (message: string) => void } = {}): Promise<{ gameId: string; title: string; gameDir: string }> {
  if (!/^[a-z0-9][a-z0-9-]*$/.test(gameId)) {
    throw new Error(`Invalid gameId "${gameId}". Use lowercase letters, numbers and hyphens, for example "midnight-cafe".`)
  }

  const gameDir = join(ROOT, 'games', gameId)
  if (existsSync(gameDir)) {
    throw new Error(`Game "${gameId}" already exists at games/${gameId}/`)
  }

  title ??= deriveTitle(gameId)
  const log = options.log ?? (() => undefined)

  log(`\n🎬 Scaffolding new game: "${title}" (${gameId})\n`)

  // index.html
  write(join(gameDir, 'index.html'), `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <link rel="stylesheet" href="../../framework/styles/base.css">
</head>
<body>
  <div id="root"></div>
  <script type="module">
    import config from './game.config.ts'
    import { GameEngine, mountVnApp } from '../../framework/index.ts'

    const engine = await GameEngine.init(config)
    mountVnApp(engine, document.getElementById('root'))
  </script>
</body>
</html>
`)

  // game.config.ts
  write(join(gameDir, 'game.config.ts'), `// games/${gameId}/game.config.ts
import type { GameConfig } from '../../framework/types.ts'

const config: GameConfig = {
  id:          '${gameId}',
  title:       '${title}',
  version:     '0.1.0',

  story: {
    defaultLocale: 'en',
    locales: {
      en: './story/en/main.ink',
    },
  },

  data: {
    characters: './data/characters/',
    scenes:     './data/scenes/',
    audio:      './data/audio/',
  },

  minigames: {},

  theme: {
    font:     '"Georgia", serif',
    dialogBg: 'rgba(10, 10, 20, 0.85)',
    accent:   '#c084fc',
    cssVars:  {},
  },

  saves: {
    slots:    5,
    autoSave: true,
  },

  distribution: {
    mode:     'standalone',
    basePath: '/${gameId}',
  },
}

export default config
`)

  // story/en/main.ink
  write(join(gameDir, 'story/en/main.ink'), `// ${title} - Main Story
INCLUDE chapter_01.ink

-> chapter_01
`)

  // story/en/chapter_01.ink
  write(join(gameDir, 'story/en/chapter_01.ink'), `// Chapter 1
=== chapter_01 ===
# scene: default
Welcome to ${title}.
Your story begins here.
-> DONE
`)

  write(join(gameDir, 'data/scenes/default.md'), `---
id: default
name: Default Scene
background:
  type: static
  image: scenes/default/background.svg
---

Starter scene generated by \`bun manager/cli.ts new ${gameId}\`.
`)

  write(join(gameDir, 'assets/scenes/default/background.svg'), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 900" role="img" aria-label="${title} starter background">
  <defs>
    <linearGradient id="sky" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0%" stop-color="#1f2937"/>
      <stop offset="52%" stop-color="#4338ca"/>
      <stop offset="100%" stop-color="#111827"/>
    </linearGradient>
  </defs>
  <rect width="1600" height="900" fill="url(#sky)"/>
  <rect y="650" width="1600" height="250" fill="#0f172a" opacity="0.72"/>
  <circle cx="1220" cy="190" r="80" fill="#f8fafc" opacity="0.86"/>
  <path d="M0 645 C260 560 420 700 690 610 C980 510 1180 675 1600 565 L1600 900 L0 900 Z" fill="#020617" opacity="0.55"/>
</svg>
`)

  const emptyDirs = [
    'data/characters',
    'data/audio/bgm',
    'data/audio/sfx',
    'data/audio/ambience',
    'data/audio/voice',
    'data/minigames',
    'assets/characters',
    'assets/audio',
    'minigames',
  ]

  for (const dir of emptyDirs) {
    const fullPath = join(gameDir, dir)
    mkdirSync(fullPath, { recursive: true })
    writeFileSync(join(fullPath, '.gitkeep'), '')
  }

  log(`  ✓ games/${gameId}/index.html`)
  log(`  ✓ games/${gameId}/game.config.ts`)
  log(`  ✓ games/${gameId}/story/en/main.ink`)
  log(`  ✓ games/${gameId}/story/en/chapter_01.ink`)
  log(`  ✓ games/${gameId}/data/scenes/default.md`)
  log(`  ✓ games/${gameId}/assets/scenes/default/background.svg`)
  log(`  ✓ games/${gameId}/data/characters/`)
  log(`  ✓ games/${gameId}/data/audio/bgm/`)
  log(`  ✓ games/${gameId}/data/audio/sfx/`)
  log(`  ✓ games/${gameId}/data/audio/ambience/`)
  log(`  ✓ games/${gameId}/data/audio/voice/`)
  log(`  ✓ games/${gameId}/data/minigames/`)
  log(`  ✓ games/${gameId}/assets/characters/`)
  log(`  ✓ games/${gameId}/assets/audio/`)
  log(`  ✓ games/${gameId}/minigames/`)

  log(`
✅ Game "${title}" created!

Next steps:
  1. bun manager/cli.ts doctor ${gameId}  — validate the starter project
  2. bun manager/cli.ts dev ${gameId}     — start dev server
  3. Edit games/${gameId}/story/en/chapter_01.ink
  4. Add characters, audio and scenes under games/${gameId}/data/
`)

  return { gameId, title, gameDir }
}

export async function newGame(gameId?: string, title?: string): Promise<void> {
  if (!gameId) {
    throw new Error('Usage: bun manager/cli.ts new <gameId> [title]\nExample: bun manager/cli.ts new midnight-cafe "The Midnight Cafe"')
  }

  await scaffoldNewGame(gameId, title, { log: message => console.log(message) })
}
